lr0: 0.01
lrf: 0.05
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3
warmup_bias_lr: 0.05
box: 7.5
cls: 0.5
hsv_h: 0.005
hsv_s: 0.5
hsv_v: 0.3
degrees: 0.0
translate: 0.02
scale: 0.2
shear: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.7
mixup: 0.05
copy_paste: 0.0
